import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.attractions': 'Atrativos',
    'nav.crafts': 'Artesanato',
    'nav.offer': 'O que Oferecemos',
    'nav.howItWorks': 'Como Funciona',
    'nav.roadmap': 'Roadmap',
    'nav.blog': 'Blog',
    'nav.contact': 'Contato',
    'nav.registerProperty': 'Cadastre sua Propriedade',
    'nav.languageLabel': 'Idioma / Language',
    'nav.subtitle': 'Turismo Rural e Artesanato Brasileiro',

    // Search
    'search.placeholder': 'Buscar atrativo ou cidade...',
    'search.searching': 'Buscando...',
    'search.noResults': 'Nenhum atrativo encontrado.',

    // Hero
    'hero.badge': 'Turismo Rural',
    'hero.title': 'Turismo Rural e Experiências',
    'hero.titleHighlight': 'Autênticas no Brasil',
    'hero.subtitle': 'Descubra fazendas para visitar, sítios, experiências no campo e artesanato regional — tudo em um só lugar.',
    'hero.ctaExplore': 'Explorar atrativos',

    // Booking Bar
    'booking.badge': 'Reserve sua Experiência',
    'booking.title': 'Agende seus Atrativos Turísticos',
    'booking.subtitle': 'Encontre e reserve as melhores experiências rurais do Brasil',
    'booking.destination': 'Destino',
    'booking.destinationPlaceholder': 'Digite o nome da propriedade...',
    'booking.visitDate': 'Data da Visita',
    'booking.people': 'Pessoas',
    'booking.peopleQuestion': 'Quantas pessoas?',
    'booking.person': 'pessoa',
    'booking.persons': 'pessoas',
    'booking.moreThan10': 'Mais de 10 pessoas',
    'booking.search': 'Buscar',
    'booking.selectDestination': 'Selecione um destino',
    'booking.selectDestinationDesc': 'Por favor, selecione uma propriedade da lista.',

    // Stats
    'stats.attractions': 'Atrativos Turísticos Rurais',
    'stats.cities': 'Cidades Parceiras',
    'stats.artisans': 'Artesãos Cadastrados',

    // PlataformaResumo
    'platform.title': 'Como Funciona o Turismo Rural na Rural Time',
    'platform.subtitle': 'Conectamos turistas a produtores rurais de forma simples e segura',
    'platform.forTourists': 'Para Turistas',
    'platform.forProducers': 'Para Produtores',
    'platform.tourist1': 'Experiências autênticas no campo',
    'platform.tourist2': 'Reservas online com segurança',
    'platform.tourist3': 'Roteiros personalizados',
    'platform.producer1': 'Cadastro gratuito de propriedades',
    'platform.producer2': 'Marketing digital e divulgação',
    'platform.producer3': 'Relatórios e rede de parceiros',
    'platform.cnaProject': 'Projeto alinhado ao Programa CNA Jovem — 6ª Edição São Paulo',
    'platform.supply': 'Oferta',
    'platform.diversification': 'Diversificação',
    'platform.collaboration': 'Colaboração',
    'platform.technology': 'Tecnologia',

    // Atrativos
    'atrativos.title': 'Atrativos Turísticos Rurais',
    'atrativos.subtitle': 'Fazendas para visitar, sítios e propriedades rurais em todo o Brasil — descubra experiências autênticas no campo.',
    'atrativos.viewAll': 'Ver Todos os Atrativos',
    'atrativos.viewMore': 'Ver mais',
    'atrativos.empty': 'Em breve teremos propriedades cadastradas com fotos para mostrar aqui.',
    'atrativos.emptyTitle': 'Atrativos da Região',

    // Artesanatos
    'artesanatos.title': 'Artesanato Rural Brasileiro',
    'artesanatos.subtitle': 'Descubra peças únicas de artesanato local criadas por talentosos artesãos do campo brasileiro.',
    'artesanatos.viewAll': 'Ver Todos os Artesanatos',
    'artesanatos.viewDetails': 'Ver detalhes',
    'artesanatos.emptyTitle': 'Artesanato Brasileiro',
    'artesanatos.empty': 'Em breve, artesanatos únicos da nossa região estarão disponíveis aqui.',

    // Blog
    'blog.title': 'Blog de Turismo Rural',
    'blog.subtitle': 'Dicas, roteiros e guias sobre experiências no campo brasileiro',
    'blog.viewAll': 'Ver Todos os Posts',

    // ComoFunciona
    'howItWorks.title': 'Como Funciona',
    'howItWorks.subtitle': 'Processo simples e eficiente para conectar campo e cidade',
    'howItWorks.step1.title': 'Produtor Cadastra',
    'howItWorks.step1.desc': 'O produtor rural cadastra sua propriedade e as experiências que oferece, como visitas guiadas, degustações e atividades interativas.',
    'howItWorks.step2.title': 'Turista Encontra',
    'howItWorks.step2.desc': 'O turista navega pela plataforma, descobre experiências que despertam seu interesse e faz a reserva online de forma segura.',
    'howItWorks.step3.title': 'A Experiência Acontece!',
    'howItWorks.step3.desc': 'No dia agendado, o turista visita a propriedade rural e vive uma experiência única no campo, criando memórias especiais e contribuindo para a economia local.',

    // Oferecemos
    'offer.title': 'O que Oferecemos',
    'offer.subtitle': 'Soluções completas para turistas e produtores rurais',
    'offer.forTourists': 'Para Turistas',
    'offer.forProducers': 'Para Produtores Rurais',
    'offer.authentic.title': 'Experiências Autênticas',
    'offer.authentic.desc': 'Descubra vivências únicas no campo, desde ordenha de vacas até colheitas sazonais e culinária rural tradicional.',
    'offer.booking.title': 'Reservas Online',
    'offer.booking.desc': 'Plataforma intuitiva para encontrar, reservar e pagar experiências rurais com segurança e praticidade.',
    'offer.freeRegister.title': 'Cadastro Gratuito',
    'offer.freeRegister.desc': 'Cadastre sua propriedade e experiências sem custos. Comece a receber turistas e diversificar sua renda.',
    'offer.marketing.title': 'Marketing Digital',
    'offer.marketing.desc': 'Apoio completo para promover sua propriedade online, com fotografias profissionais e estratégias de divulgação.',
    'offer.reports.title': 'Relatórios e Rede',
    'offer.reports.desc': 'Acesse relatórios de desempenho e conecte-se com outros produtores para trocar experiências e boas práticas.',

    // Beneficios
    'benefits.title': 'Benefícios para Todos',
    'benefits.subtitle': 'Impacto positivo que transforma vidas e comunidades',
    'benefits.countryside.title': 'Para o Campo',
    'benefits.countryside.income': 'Diversificação da Renda',
    'benefits.countryside.incomeDesc': 'Nova fonte de receita complementar às atividades agrícolas tradicionais.',
    'benefits.countryside.culture': 'Valorização Cultural',
    'benefits.countryside.cultureDesc': 'Preservação e divulgação das tradições e conhecimentos rurais.',
    'benefits.countryside.digital': 'Transformação Digital',
    'benefits.countryside.digitalDesc': 'Acesso facilitado às tecnologias digitais e marketing online.',
    'benefits.city.title': 'Para a Cidade',
    'benefits.city.authentic': 'Experiências Autênticas',
    'benefits.city.authenticDesc': 'Conexão verdadeira com a natureza e modos de vida rurais.',
    'benefits.city.education': 'Educação Rural',
    'benefits.city.educationDesc': 'Aprendizado sobre agricultura, pecuária e sustentabilidade.',
    'benefits.city.wellbeing': 'Bem-estar',
    'benefits.city.wellbeingDesc': 'Momentos de descanso e reconexão longe do estresse urbano.',
    'benefits.society.title': 'Para a Sociedade',
    'benefits.society.sustainability': 'Sustentabilidade',
    'benefits.society.sustainabilityDesc': 'Promoção de práticas ambientalmente responsáveis e conscientes.',
    'benefits.society.economy': 'Economia Local',
    'benefits.society.economyDesc': 'Fortalecimento da economia regional e geração de empregos.',
    'benefits.society.integration': 'Integração Social',
    'benefits.society.integrationDesc': 'Aproximação entre diferentes realidades e culturas.',

    // QuemSomos
    'about.title': 'Sobre a Rural Time — Turismo Rural Digital',
    'about.subtitle': 'Uma iniciativa que nasceu da paixão pelo campo e pela inovação no agro brasileiro',
    'about.founder': 'Fundador',
    'about.founderBio': 'Formado em Engenharia e Tecnologia, com especialização em Agronegócio e Marketing Digital. Reconhecido pela Forbes Under 30 por sua inovação no agro, atua como instrutor do SENAR e é fundador da RuralTime.com.br.',

    // Depoimentos
    'testimonials.title': 'Depoimentos de Turismo Rural',
    'testimonials.subtitle': 'Histórias reais de turistas e produtores rurais que fazem parte da Rural Time',
    'testimonials.cta': 'Quer compartilhar sua experiência?',
    'testimonials.send': 'Envie seu depoimento',
    'testimonials.1.text': 'O Rural Time transformou nossa propriedade. Agora recebemos famílias da cidade que se encantam com nossa rotina e ainda geram uma renda extra importante para nossa família.',
    'testimonials.1.type': 'Produtora Rural',
    'testimonials.2.text': 'Foi incrível! Meus filhos aprenderam de onde vem o leite, participaram da ordenha e se divertiram muito. Uma experiência educativa que toda família deveria viver.',
    'testimonials.2.type': 'Turista',
    'testimonials.3.text': 'A plataforma é muito fácil de usar. Em poucos minutos consegui cadastrar minha propriedade e já estou recebendo as primeiras reservas. Tecnologia que realmente funciona!',
    'testimonials.3.type': 'Produtor Rural',

    // ImpactoCNA
    'cna.title': 'Impacto CNA Jovem',
    'cna.subtitle': 'Alinhado aos objetivos do programa, gerando transformação real no agronegócio',
    'cna.supply': 'Aumento da Oferta',
    'cna.supplyDesc': 'Aumentar o número de propriedades ofertando turismo rural em todo o Brasil.',
    'cna.diversification': 'Diversificação',
    'cna.diversificationDesc': 'Ampliar a renda do produtor rural através de atividades complementares sustentáveis.',
    'cna.collaboration': 'Colaboração',
    'cna.collaborationDesc': 'Aumentar a colaboração entre sindicatos, federações e produtores rurais.',
    'cna.technology': 'Tecnologia',
    'cna.technologyDesc': 'Reduzir barreiras de acesso à tecnologia digital no campo.',
    'cna.editionTitle': 'CNA Jovem - 6ª Edição São Paulo',
    'cna.editionDesc': 'O Rural Time representa o espírito inovador e empreendedor do Programa CNA Jovem, combinando tradição rural com tecnologia moderna para criar soluções que beneficiam toda a cadeia produtiva do agronegócio brasileiro.',
    'cna.aProject': 'Um projeto',
    'cna.goal': 'Meta:',

    // Contato
    'contact.title': 'Contato',
    'contact.subtitle': 'Entre em contato conosco e faça parte da transformação do turismo rural',
    'contact.location': 'Localização',
    'contact.email': 'E-mail',
    'contact.socialTitle': 'Siga-nos nas Redes Sociais',
    'contact.socialSubtitle': 'Acompanhe novidades, dicas e histórias inspiradoras do campo',

    // SejaParceiro
    'partner.title': 'Pronto para começar?',
    'partner.subtitle': 'Faça parte da maior rede de turismo rural do Brasil',
    'partner.iamTourist': 'Sou Turista',
    'partner.iamProducer': 'Sou Produtor',
    'partner.why': 'Por que ser nosso parceiro?',
    'partner.unions': 'Sindicatos Rurais',
    'partner.unionsDesc': 'Ampliem o alcance dos serviços aos associados e fortaleçam a economia local.',
    'partner.cooperatives': 'Cooperativas',
    'partner.cooperativesDesc': 'Oferecemos oportunidades de diversificação de negócios para cooperados.',
    'partner.institutions': 'Instituições',
    'partner.institutionsDesc': 'Apoiem projetos que promovem sustentabilidade e desenvolvimento rural.',
    'partner.supporters': 'Apoiadores',
    'partner.supportersDesc': 'Contribuam para a transformação digital do agronegócio brasileiro.',
    'partner.contactTitle': 'Entre em Contato',
    'partner.fullName': 'Nome completo',
    'partner.namePlaceholder': 'Seu nome',
    'partner.emailPlaceholder': 'seu@email.com',
    'partner.phone': 'Telefone',
    'partner.organization': 'Organização',
    'partner.orgPlaceholder': 'Nome da organização',
    'partner.partnershipType': 'Tipo de parceria',
    'partner.selectType': 'Selecione o tipo',
    'partner.typeUnion': 'Sindicato Rural',
    'partner.typeCooperative': 'Cooperativa',
    'partner.typeInstitution': 'Instituição',
    'partner.typeCompany': 'Empresa',
    'partner.typeSupporter': 'Apoiador',
    'partner.typeOther': 'Outro',
    'partner.message': 'Mensagem',
    'partner.messagePlaceholder': 'Conte-nos mais sobre sua proposta de parceria...',
    'partner.submit': 'Enviar Proposta',
    'partner.successTitle': 'Mensagem enviada!',
    'partner.successDesc': 'Entraremos em contato em breve para discutir a parceria.',

    // Apoiadores
    'supporters.our': 'Nossos',
    'supporters.label': 'apoiadores',
    'supporters.suffix': '— instituições do setor rural',

    // IncluiCampo
    'incluiCampo.title': 'Parceria IncluiCampo',
    'incluiCampo.desc': 'é uma iniciativa digital voltada ao turismo rural acessível, criada para ajudar produtores a identificar barreiras, avaliar sua propriedade e implementar melhorias práticas de acessibilidade, oferecendo diagnósticos gratuitos, recomendações personalizadas e ferramentas que tornam as experiências no campo mais inclusivas para todos.',
    'incluiCampo.cta': 'Conheça o IncluiCampo',

    // Map
    'map.title': 'Mapa do Turismo Rural no Brasil',
    'map.subtitle': 'Encontre fazendas, sítios e propriedades rurais em todos os estados. Clique para explorar destinos de turismo rural.',
    'map.states': 'Estados',
    'map.viewAllStates': 'Ver todos os estados',
    'map.allProperties': 'Todas as propriedades',
    'map.changeState': 'Trocar estado',
    'map.close': 'Fechar',
    'map.clickNavigate': 'Clique para navegar no mapa',
    'map.propertiesIn': 'Propriedades em',
    'map.viewFullDetails': 'Ver Detalhes Completos',
    'map.activities': 'Atividades:',
    'map.perPerson': '/ pessoa',

    // Footer
    'footer.desc': 'Rural Time – Plataforma de Turismo Rural e Inovação no Agro. Um projeto conectado aos valores e objetivos do CNA Jovem.',
    'footer.createdBy': 'Criado por',
    'footer.role': 'Instrutor do Senar e Líder do Agro',
    'footer.quickLinks': 'Links Rápidos',
    'footer.start': 'Início',
    'footer.aboutUs': 'Quem Somos',
    'footer.bePartner': 'Seja Parceiro',
    'footer.contact': 'Contato',
    'footer.contactTitle': 'Contato',
    'footer.rights': '© 2026 Rural Time. Todos os direitos reservados.',
    'footer.poweredBy': 'Powered by',

    // PropriedadeDetalhes
    'detail.back': 'Voltar',
    'detail.featured': 'Destaque',
    'detail.noImage': 'Sem imagem',
    'detail.about': 'Sobre',
    'detail.viewMore': 'Ver mais',
    'detail.viewLess': 'Ver menos',
    'detail.size': 'Tamanho',
    'detail.hectares': 'hectares',
    'detail.capacity': 'Capacidade',
    'detail.visitors': 'visitantes',
    'detail.visitPrice': 'Preço da visita',
    'detail.schedule': 'Horário',
    'detail.activities': 'Atividades',
    'detail.infrastructure': 'Infraestrutura',
    'detail.contact': 'Contato',
    'detail.bookVisit': 'Agendar visita',
    'detail.date': 'Data',
    'detail.selectDate': 'Selecione a data',
    'detail.people': 'Pessoas',
    'detail.person': 'pessoa',
    'detail.persons': 'pessoas',
    'detail.sendWhatsapp': 'Enviar via WhatsApp',
    'detail.notFound': 'Propriedade não encontrada',
    'detail.backHome': 'Voltar ao início',
    'detail.goToImage': 'Ir para imagem',
    'detail.thumbnail': 'miniatura',

    // General
    'general.ruralTourism': 'Turismo Rural',
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.attractions': 'Attractions',
    'nav.crafts': 'Handicrafts',
    'nav.offer': 'What We Offer',
    'nav.howItWorks': 'How It Works',
    'nav.roadmap': 'Roadmap',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.registerProperty': 'Register Your Property',
    'nav.languageLabel': 'Language',
    'nav.subtitle': 'Rural Tourism and Brazilian Handicrafts',

    // Hero
    'hero.badge': 'Rural Tourism',
    'hero.title': 'Rural Tourism and Authentic',
    'hero.titleHighlight': 'Experiences in Brazil',
    'hero.subtitle': 'Discover farms to visit, rural estates, countryside experiences and regional handicrafts — all in one place.',
    'hero.ctaExplore': 'Explore attractions',

    // Booking Bar
    'booking.badge': 'Book Your Experience',
    'booking.title': 'Schedule Your Tourist Attractions',
    'booking.subtitle': 'Find and book the best rural experiences in Brazil',
    'booking.destination': 'Destination',
    'booking.destinationPlaceholder': 'Type the property name...',
    'booking.visitDate': 'Visit Date',
    'booking.people': 'People',
    'booking.peopleQuestion': 'How many people?',
    'booking.person': 'person',
    'booking.persons': 'people',
    'booking.moreThan10': 'More than 10 people',
    'booking.search': 'Search',
    'booking.selectDestination': 'Select a destination',
    'booking.selectDestinationDesc': 'Please select a property from the list.',

    // Stats
    'stats.attractions': 'Rural Tourist Attractions',
    'stats.cities': 'Partner Cities',
    'stats.artisans': 'Registered Artisans',

    // PlataformaResumo
    'platform.title': 'How Rural Tourism Works at Rural Time',
    'platform.subtitle': 'We connect tourists to rural producers simply and safely',
    'platform.forTourists': 'For Tourists',
    'platform.forProducers': 'For Producers',
    'platform.tourist1': 'Authentic countryside experiences',
    'platform.tourist2': 'Secure online bookings',
    'platform.tourist3': 'Personalized itineraries',
    'platform.producer1': 'Free property registration',
    'platform.producer2': 'Digital marketing and promotion',
    'platform.producer3': 'Reports and partner network',
    'platform.cnaProject': 'Project aligned with the CNA Jovem Program — 6th Edition São Paulo',
    'platform.supply': 'Supply',
    'platform.diversification': 'Diversification',
    'platform.collaboration': 'Collaboration',
    'platform.technology': 'Technology',

    // Atrativos
    'atrativos.title': 'Rural Tourist Attractions',
    'atrativos.subtitle': 'Farms, estates and rural properties across Brazil — discover authentic countryside experiences.',
    'atrativos.viewAll': 'View All Attractions',
    'atrativos.viewMore': 'View more',
    'atrativos.empty': 'Soon we will have registered properties with photos to show here.',
    'atrativos.emptyTitle': 'Regional Attractions',

    // Artesanatos
    'artesanatos.title': 'Brazilian Rural Handicrafts',
    'artesanatos.subtitle': 'Discover unique local handicraft pieces created by talented artisans from the Brazilian countryside.',
    'artesanatos.viewAll': 'View All Handicrafts',
    'artesanatos.viewDetails': 'View details',
    'artesanatos.emptyTitle': 'Brazilian Handicrafts',
    'artesanatos.empty': 'Soon, unique handicrafts from our region will be available here.',

    // Blog
    'blog.title': 'Rural Tourism Blog',
    'blog.subtitle': 'Tips, itineraries and guides about experiences in the Brazilian countryside',
    'blog.viewAll': 'View All Posts',

    // ComoFunciona
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Simple and efficient process to connect countryside and city',
    'howItWorks.step1.title': 'Producer Registers',
    'howItWorks.step1.desc': 'The rural producer registers their property and the experiences they offer, such as guided tours, tastings and interactive activities.',
    'howItWorks.step2.title': 'Tourist Discovers',
    'howItWorks.step2.desc': 'The tourist browses the platform, discovers experiences that spark their interest and makes a secure online booking.',
    'howItWorks.step3.title': 'The Experience Happens!',
    'howItWorks.step3.desc': 'On the scheduled day, the tourist visits the rural property and lives a unique countryside experience, creating special memories and contributing to the local economy.',

    // Oferecemos
    'offer.title': 'What We Offer',
    'offer.subtitle': 'Complete solutions for tourists and rural producers',
    'offer.forTourists': 'For Tourists',
    'offer.forProducers': 'For Rural Producers',
    'offer.authentic.title': 'Authentic Experiences',
    'offer.authentic.desc': 'Discover unique countryside experiences, from cow milking to seasonal harvests and traditional rural cuisine.',
    'offer.booking.title': 'Online Bookings',
    'offer.booking.desc': 'Intuitive platform to find, book and pay for rural experiences with security and convenience.',
    'offer.freeRegister.title': 'Free Registration',
    'offer.freeRegister.desc': 'Register your property and experiences at no cost. Start receiving tourists and diversifying your income.',
    'offer.marketing.title': 'Digital Marketing',
    'offer.marketing.desc': 'Full support to promote your property online, with professional photography and marketing strategies.',
    'offer.reports.title': 'Reports and Network',
    'offer.reports.desc': 'Access performance reports and connect with other producers to share experiences and best practices.',

    // Beneficios
    'benefits.title': 'Benefits for Everyone',
    'benefits.subtitle': 'Positive impact that transforms lives and communities',
    'benefits.countryside.title': 'For the Countryside',
    'benefits.countryside.income': 'Income Diversification',
    'benefits.countryside.incomeDesc': 'New revenue source complementing traditional agricultural activities.',
    'benefits.countryside.culture': 'Cultural Appreciation',
    'benefits.countryside.cultureDesc': 'Preservation and promotion of rural traditions and knowledge.',
    'benefits.countryside.digital': 'Digital Transformation',
    'benefits.countryside.digitalDesc': 'Easier access to digital technologies and online marketing.',
    'benefits.city.title': 'For the City',
    'benefits.city.authentic': 'Authentic Experiences',
    'benefits.city.authenticDesc': 'True connection with nature and rural ways of life.',
    'benefits.city.education': 'Rural Education',
    'benefits.city.educationDesc': 'Learning about agriculture, livestock and sustainability.',
    'benefits.city.wellbeing': 'Well-being',
    'benefits.city.wellbeingDesc': 'Moments of rest and reconnection away from urban stress.',
    'benefits.society.title': 'For Society',
    'benefits.society.sustainability': 'Sustainability',
    'benefits.society.sustainabilityDesc': 'Promotion of environmentally responsible and conscious practices.',
    'benefits.society.economy': 'Local Economy',
    'benefits.society.economyDesc': 'Strengthening the regional economy and job creation.',
    'benefits.society.integration': 'Social Integration',
    'benefits.society.integrationDesc': 'Bridging different realities and cultures.',

    // QuemSomos
    'about.title': 'About Rural Time — Digital Rural Tourism',
    'about.subtitle': 'An initiative born from the passion for the countryside and innovation in Brazilian agribusiness',
    'about.founder': 'Founder',
    'about.founderBio': 'Graduated in Engineering and Technology, specializing in Agribusiness and Digital Marketing. Recognized by Forbes Under 30 for his innovation in agribusiness, he works as a SENAR instructor and is the founder of RuralTime.com.br.',

    // Depoimentos
    'testimonials.title': 'Rural Tourism Testimonials',
    'testimonials.subtitle': 'Real stories from tourists and rural producers who are part of Rural Time',
    'testimonials.cta': 'Want to share your experience?',
    'testimonials.send': 'Send your testimonial',
    'testimonials.1.text': 'Rural Time transformed our property. Now we welcome families from the city who are enchanted by our routine and generate important extra income for our family.',
    'testimonials.1.type': 'Rural Producer',
    'testimonials.2.text': 'It was amazing! My children learned where milk comes from, participated in milking and had a lot of fun. An educational experience every family should live.',
    'testimonials.2.type': 'Tourist',
    'testimonials.3.text': 'The platform is very easy to use. In a few minutes I was able to register my property and I\'m already receiving the first bookings. Technology that really works!',
    'testimonials.3.type': 'Rural Producer',

    // ImpactoCNA
    'cna.title': 'CNA Jovem Impact',
    'cna.subtitle': 'Aligned with program objectives, generating real transformation in agribusiness',
    'cna.supply': 'Supply Increase',
    'cna.supplyDesc': 'Increase the number of properties offering rural tourism across Brazil.',
    'cna.diversification': 'Diversification',
    'cna.diversificationDesc': 'Expand rural producer income through sustainable complementary activities.',
    'cna.collaboration': 'Collaboration',
    'cna.collaborationDesc': 'Increase collaboration between unions, federations and rural producers.',
    'cna.technology': 'Technology',
    'cna.technologyDesc': 'Reduce barriers to digital technology access in the countryside.',
    'cna.editionTitle': 'CNA Jovem - 6th Edition São Paulo',
    'cna.editionDesc': 'Rural Time represents the innovative and entrepreneurial spirit of the CNA Jovem Program, combining rural tradition with modern technology to create solutions that benefit the entire Brazilian agribusiness production chain.',
    'cna.aProject': 'A project',
    'cna.goal': 'Goal:',

    // Contato
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with us and be part of the rural tourism transformation',
    'contact.location': 'Location',
    'contact.email': 'Email',
    'contact.socialTitle': 'Follow Us on Social Media',
    'contact.socialSubtitle': 'Follow news, tips and inspiring stories from the countryside',

    // SejaParceiro
    'partner.title': 'Ready to get started?',
    'partner.subtitle': 'Be part of the largest rural tourism network in Brazil',
    'partner.iamTourist': 'I\'m a Tourist',
    'partner.iamProducer': 'I\'m a Producer',
    'partner.why': 'Why be our partner?',
    'partner.unions': 'Rural Unions',
    'partner.unionsDesc': 'Expand the reach of services to members and strengthen the local economy.',
    'partner.cooperatives': 'Cooperatives',
    'partner.cooperativesDesc': 'We offer business diversification opportunities for cooperative members.',
    'partner.institutions': 'Institutions',
    'partner.institutionsDesc': 'Support projects that promote sustainability and rural development.',
    'partner.supporters': 'Supporters',
    'partner.supportersDesc': 'Contribute to the digital transformation of Brazilian agribusiness.',
    'partner.contactTitle': 'Get in Touch',
    'partner.fullName': 'Full name',
    'partner.namePlaceholder': 'Your name',
    'partner.emailPlaceholder': 'your@email.com',
    'partner.phone': 'Phone',
    'partner.organization': 'Organization',
    'partner.orgPlaceholder': 'Organization name',
    'partner.partnershipType': 'Partnership type',
    'partner.selectType': 'Select type',
    'partner.typeUnion': 'Rural Union',
    'partner.typeCooperative': 'Cooperative',
    'partner.typeInstitution': 'Institution',
    'partner.typeCompany': 'Company',
    'partner.typeSupporter': 'Supporter',
    'partner.typeOther': 'Other',
    'partner.message': 'Message',
    'partner.messagePlaceholder': 'Tell us more about your partnership proposal...',
    'partner.submit': 'Send Proposal',
    'partner.successTitle': 'Message sent!',
    'partner.successDesc': 'We will contact you soon to discuss the partnership.',

    // Apoiadores
    'supporters.our': 'Our',
    'supporters.label': 'supporters',
    'supporters.suffix': '— rural sector institutions',

    // IncluiCampo
    'incluiCampo.title': 'IncluiCampo Partnership',
    'incluiCampo.desc': 'is a digital initiative focused on accessible rural tourism, created to help producers identify barriers, evaluate their property and implement practical accessibility improvements, offering free diagnostics, personalized recommendations and tools that make countryside experiences more inclusive for everyone.',
    'incluiCampo.cta': 'Learn about IncluiCampo',

    // Map
    'map.title': 'Rural Tourism Map of Brazil',
    'map.subtitle': 'Find farms, estates and rural properties in all states. Click to explore rural tourism destinations.',
    'map.states': 'States',
    'map.viewAllStates': 'View all states',
    'map.allProperties': 'All properties',
    'map.changeState': 'Change state',
    'map.close': 'Close',
    'map.clickNavigate': 'Click to navigate the map',
    'map.propertiesIn': 'Properties in',
    'map.viewFullDetails': 'View Full Details',
    'map.activities': 'Activities:',
    'map.perPerson': '/ person',

    // Footer
    'footer.desc': 'Rural Time – Rural Tourism and Agro Innovation Platform. A project connected to the values and objectives of CNA Jovem.',
    'footer.createdBy': 'Created by',
    'footer.role': 'SENAR Instructor and Agro Leader',
    'footer.quickLinks': 'Quick Links',
    'footer.start': 'Home',
    'footer.aboutUs': 'About Us',
    'footer.bePartner': 'Be a Partner',
    'footer.contact': 'Contact',
    'footer.contactTitle': 'Contact',
    'footer.rights': '© 2026 Rural Time. All rights reserved.',
    'footer.poweredBy': 'Powered by',

    // PropriedadeDetalhes
    'detail.back': 'Back',
    'detail.featured': 'Featured',
    'detail.noImage': 'No image',
    'detail.about': 'About',
    'detail.viewMore': 'View more',
    'detail.viewLess': 'View less',
    'detail.size': 'Size',
    'detail.hectares': 'hectares',
    'detail.capacity': 'Capacity',
    'detail.visitors': 'visitors',
    'detail.visitPrice': 'Visit price',
    'detail.schedule': 'Schedule',
    'detail.activities': 'Activities',
    'detail.infrastructure': 'Infrastructure',
    'detail.contact': 'Contact',
    'detail.bookVisit': 'Book a visit',
    'detail.date': 'Date',
    'detail.selectDate': 'Select a date',
    'detail.people': 'People',
    'detail.person': 'person',
    'detail.persons': 'people',
    'detail.sendWhatsapp': 'Send via WhatsApp',
    'detail.notFound': 'Property not found',
    'detail.backHome': 'Back to home',
    'detail.goToImage': 'Go to image',
    'detail.thumbnail': 'thumbnail',

    // General
    'general.ruralTourism': 'Rural Tourism',
  },

  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.attractions': 'Atractivos',
    'nav.crafts': 'Artesanía',
    'nav.offer': 'Qué Ofrecemos',
    'nav.howItWorks': 'Cómo Funciona',
    'nav.roadmap': 'Hoja de Ruta',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacto',
    'nav.registerProperty': 'Registre su Propiedad',
    'nav.languageLabel': 'Idioma',
    'nav.subtitle': 'Turismo Rural y Artesanía Brasileña',

    // Hero
    'hero.badge': 'Turismo Rural',
    'hero.title': 'Turismo Rural y Experiencias',
    'hero.titleHighlight': 'Auténticas en Brasil',
    'hero.subtitle': 'Descubra fincas para visitar, estancias, experiencias en el campo y artesanía regional — todo en un solo lugar.',
    'hero.ctaExplore': 'Explorar atractivos',

    // Booking Bar
    'booking.badge': 'Reserve su Experiencia',
    'booking.title': 'Programe sus Atractivos Turísticos',
    'booking.subtitle': 'Encuentre y reserve las mejores experiencias rurales de Brasil',
    'booking.destination': 'Destino',
    'booking.destinationPlaceholder': 'Escriba el nombre de la propiedad...',
    'booking.visitDate': 'Fecha de Visita',
    'booking.people': 'Personas',
    'booking.peopleQuestion': '¿Cuántas personas?',
    'booking.person': 'persona',
    'booking.persons': 'personas',
    'booking.moreThan10': 'Más de 10 personas',
    'booking.search': 'Buscar',
    'booking.selectDestination': 'Seleccione un destino',
    'booking.selectDestinationDesc': 'Por favor, seleccione una propiedad de la lista.',

    // Stats
    'stats.attractions': 'Atractivos Turísticos Rurales',
    'stats.cities': 'Ciudades Asociadas',
    'stats.artisans': 'Artesanos Registrados',

    // PlataformaResumo
    'platform.title': 'Cómo Funciona el Turismo Rural en Rural Time',
    'platform.subtitle': 'Conectamos turistas con productores rurales de forma simple y segura',
    'platform.forTourists': 'Para Turistas',
    'platform.forProducers': 'Para Productores',
    'platform.tourist1': 'Experiencias auténticas en el campo',
    'platform.tourist2': 'Reservas online con seguridad',
    'platform.tourist3': 'Itinerarios personalizados',
    'platform.producer1': 'Registro gratuito de propiedades',
    'platform.producer2': 'Marketing digital y divulgación',
    'platform.producer3': 'Informes y red de socios',
    'platform.cnaProject': 'Proyecto alineado con el Programa CNA Jovem — 6ª Edición São Paulo',
    'platform.supply': 'Oferta',
    'platform.diversification': 'Diversificación',
    'platform.collaboration': 'Colaboración',
    'platform.technology': 'Tecnología',

    // Atrativos
    'atrativos.title': 'Atractivos Turísticos Rurales',
    'atrativos.subtitle': 'Fincas, estancias y propiedades rurales en todo Brasil — descubra experiencias auténticas en el campo.',
    'atrativos.viewAll': 'Ver Todos los Atractivos',
    'atrativos.viewMore': 'Ver más',
    'atrativos.empty': 'Pronto tendremos propiedades registradas con fotos para mostrar aquí.',
    'atrativos.emptyTitle': 'Atractivos de la Región',

    // Artesanatos
    'artesanatos.title': 'Artesanía Rural Brasileña',
    'artesanatos.subtitle': 'Descubra piezas únicas de artesanía local creadas por talentosos artesanos del campo brasileño.',
    'artesanatos.viewAll': 'Ver Todas las Artesanías',
    'artesanatos.viewDetails': 'Ver detalles',
    'artesanatos.emptyTitle': 'Artesanía Brasileña',
    'artesanatos.empty': 'Pronto, artesanías únicas de nuestra región estarán disponibles aquí.',

    // Blog
    'blog.title': 'Blog de Turismo Rural',
    'blog.subtitle': 'Consejos, itinerarios y guías sobre experiencias en el campo brasileño',
    'blog.viewAll': 'Ver Todos los Posts',

    // ComoFunciona
    'howItWorks.title': 'Cómo Funciona',
    'howItWorks.subtitle': 'Proceso simple y eficiente para conectar campo y ciudad',
    'howItWorks.step1.title': 'El Productor Registra',
    'howItWorks.step1.desc': 'El productor rural registra su propiedad y las experiencias que ofrece, como visitas guiadas, degustaciones y actividades interactivas.',
    'howItWorks.step2.title': 'El Turista Descubre',
    'howItWorks.step2.desc': 'El turista navega por la plataforma, descubre experiencias que despiertan su interés y realiza la reserva online de forma segura.',
    'howItWorks.step3.title': '¡La Experiencia Ocurre!',
    'howItWorks.step3.desc': 'En el día programado, el turista visita la propiedad rural y vive una experiencia única en el campo, creando recuerdos especiales y contribuyendo a la economía local.',

    // Oferecemos
    'offer.title': 'Qué Ofrecemos',
    'offer.subtitle': 'Soluciones completas para turistas y productores rurales',
    'offer.forTourists': 'Para Turistas',
    'offer.forProducers': 'Para Productores Rurales',
    'offer.authentic.title': 'Experiencias Auténticas',
    'offer.authentic.desc': 'Descubra vivencias únicas en el campo, desde ordeñar vacas hasta cosechas estacionales y cocina rural tradicional.',
    'offer.booking.title': 'Reservas Online',
    'offer.booking.desc': 'Plataforma intuitiva para encontrar, reservar y pagar experiencias rurales con seguridad y practicidad.',
    'offer.freeRegister.title': 'Registro Gratuito',
    'offer.freeRegister.desc': 'Registre su propiedad y experiencias sin costos. Comience a recibir turistas y diversificar sus ingresos.',
    'offer.marketing.title': 'Marketing Digital',
    'offer.marketing.desc': 'Apoyo completo para promover su propiedad online, con fotografías profesionales y estrategias de divulgación.',
    'offer.reports.title': 'Informes y Red',
    'offer.reports.desc': 'Acceda a informes de desempeño y conéctese con otros productores para intercambiar experiencias y buenas prácticas.',

    // Beneficios
    'benefits.title': 'Beneficios para Todos',
    'benefits.subtitle': 'Impacto positivo que transforma vidas y comunidades',
    'benefits.countryside.title': 'Para el Campo',
    'benefits.countryside.income': 'Diversificación de Ingresos',
    'benefits.countryside.incomeDesc': 'Nueva fuente de ingresos complementaria a las actividades agrícolas tradicionales.',
    'benefits.countryside.culture': 'Valoración Cultural',
    'benefits.countryside.cultureDesc': 'Preservación y divulgación de las tradiciones y conocimientos rurales.',
    'benefits.countryside.digital': 'Transformación Digital',
    'benefits.countryside.digitalDesc': 'Acceso facilitado a las tecnologías digitales y marketing online.',
    'benefits.city.title': 'Para la Ciudad',
    'benefits.city.authentic': 'Experiencias Auténticas',
    'benefits.city.authenticDesc': 'Conexión verdadera con la naturaleza y los modos de vida rurales.',
    'benefits.city.education': 'Educación Rural',
    'benefits.city.educationDesc': 'Aprendizaje sobre agricultura, ganadería y sustentabilidad.',
    'benefits.city.wellbeing': 'Bienestar',
    'benefits.city.wellbeingDesc': 'Momentos de descanso y reconexión lejos del estrés urbano.',
    'benefits.society.title': 'Para la Sociedad',
    'benefits.society.sustainability': 'Sustentabilidad',
    'benefits.society.sustainabilityDesc': 'Promoción de prácticas ambientalmente responsables y conscientes.',
    'benefits.society.economy': 'Economía Local',
    'benefits.society.economyDesc': 'Fortalecimiento de la economía regional y generación de empleos.',
    'benefits.society.integration': 'Integración Social',
    'benefits.society.integrationDesc': 'Acercamiento entre diferentes realidades y culturas.',

    // QuemSomos
    'about.title': 'Sobre Rural Time — Turismo Rural Digital',
    'about.subtitle': 'Una iniciativa que nació de la pasión por el campo y la innovación en el agro brasileño',
    'about.founder': 'Fundador',
    'about.founderBio': 'Graduado en Ingeniería y Tecnología, con especialización en Agronegocios y Marketing Digital. Reconocido por Forbes Under 30 por su innovación en el agro, actúa como instructor del SENAR y es fundador de RuralTime.com.br.',

    // Depoimentos
    'testimonials.title': 'Testimonios de Turismo Rural',
    'testimonials.subtitle': 'Historias reales de turistas y productores rurales que forman parte de Rural Time',
    'testimonials.cta': '¿Quieres compartir tu experiencia?',
    'testimonials.send': 'Envía tu testimonio',
    'testimonials.1.text': 'Rural Time transformó nuestra propiedad. Ahora recibimos familias de la ciudad que se encantan con nuestra rutina y generan un ingreso extra importante para nuestra familia.',
    'testimonials.1.type': 'Productora Rural',
    'testimonials.2.text': '¡Fue increíble! Mis hijos aprendieron de dónde viene la leche, participaron en el ordeño y se divirtieron mucho. Una experiencia educativa que toda familia debería vivir.',
    'testimonials.2.type': 'Turista',
    'testimonials.3.text': 'La plataforma es muy fácil de usar. En pocos minutos logré registrar mi propiedad y ya estoy recibiendo las primeras reservas. ¡Tecnología que realmente funciona!',
    'testimonials.3.type': 'Productor Rural',

    // ImpactoCNA
    'cna.title': 'Impacto CNA Jovem',
    'cna.subtitle': 'Alineado con los objetivos del programa, generando transformación real en el agronegocio',
    'cna.supply': 'Aumento de la Oferta',
    'cna.supplyDesc': 'Aumentar el número de propiedades que ofrecen turismo rural en todo Brasil.',
    'cna.diversification': 'Diversificación',
    'cna.diversificationDesc': 'Ampliar los ingresos del productor rural a través de actividades complementarias sustentables.',
    'cna.collaboration': 'Colaboración',
    'cna.collaborationDesc': 'Aumentar la colaboración entre sindicatos, federaciones y productores rurales.',
    'cna.technology': 'Tecnología',
    'cna.technologyDesc': 'Reducir barreras de acceso a la tecnología digital en el campo.',
    'cna.editionTitle': 'CNA Jovem - 6ª Edición São Paulo',
    'cna.editionDesc': 'Rural Time representa el espíritu innovador y emprendedor del Programa CNA Jovem, combinando tradición rural con tecnología moderna para crear soluciones que benefician toda la cadena productiva del agronegocio brasileño.',
    'cna.aProject': 'Un proyecto',
    'cna.goal': 'Meta:',

    // Contato
    'contact.title': 'Contacto',
    'contact.subtitle': 'Contáctenos y sea parte de la transformación del turismo rural',
    'contact.location': 'Ubicación',
    'contact.email': 'Correo',
    'contact.socialTitle': 'Síguenos en las Redes Sociales',
    'contact.socialSubtitle': 'Siga novedades, consejos e historias inspiradoras del campo',

    // SejaParceiro
    'partner.title': '¿Listo para comenzar?',
    'partner.subtitle': 'Sea parte de la mayor red de turismo rural de Brasil',
    'partner.iamTourist': 'Soy Turista',
    'partner.iamProducer': 'Soy Productor',
    'partner.why': '¿Por qué ser nuestro socio?',
    'partner.unions': 'Sindicatos Rurales',
    'partner.unionsDesc': 'Amplíen el alcance de los servicios a los asociados y fortalezcan la economía local.',
    'partner.cooperatives': 'Cooperativas',
    'partner.cooperativesDesc': 'Ofrecemos oportunidades de diversificación de negocios para cooperados.',
    'partner.institutions': 'Instituciones',
    'partner.institutionsDesc': 'Apoyen proyectos que promueven sustentabilidad y desarrollo rural.',
    'partner.supporters': 'Apoyadores',
    'partner.supportersDesc': 'Contribuyan a la transformación digital del agronegocio brasileño.',
    'partner.contactTitle': 'Contáctenos',
    'partner.fullName': 'Nombre completo',
    'partner.namePlaceholder': 'Su nombre',
    'partner.emailPlaceholder': 'su@email.com',
    'partner.phone': 'Teléfono',
    'partner.organization': 'Organización',
    'partner.orgPlaceholder': 'Nombre de la organización',
    'partner.partnershipType': 'Tipo de asociación',
    'partner.selectType': 'Seleccione el tipo',
    'partner.typeUnion': 'Sindicato Rural',
    'partner.typeCooperative': 'Cooperativa',
    'partner.typeInstitution': 'Institución',
    'partner.typeCompany': 'Empresa',
    'partner.typeSupporter': 'Apoyador',
    'partner.typeOther': 'Otro',
    'partner.message': 'Mensaje',
    'partner.messagePlaceholder': 'Cuéntenos más sobre su propuesta de asociación...',
    'partner.submit': 'Enviar Propuesta',
    'partner.successTitle': '¡Mensaje enviado!',
    'partner.successDesc': 'Nos pondremos en contacto pronto para discutir la asociación.',

    // Apoiadores
    'supporters.our': 'Nuestros',
    'supporters.label': 'apoyadores',
    'supporters.suffix': '— instituciones del sector rural',

    // IncluiCampo
    'incluiCampo.title': 'Asociación IncluiCampo',
    'incluiCampo.desc': 'es una iniciativa digital enfocada en el turismo rural accesible, creada para ayudar a productores a identificar barreras, evaluar su propiedad e implementar mejoras prácticas de accesibilidad, ofreciendo diagnósticos gratuitos, recomendaciones personalizadas y herramientas que hacen las experiencias en el campo más inclusivas para todos.',
    'incluiCampo.cta': 'Conozca IncluiCampo',

    // Map
    'map.title': 'Mapa del Turismo Rural en Brasil',
    'map.subtitle': 'Encuentre fincas, estancias y propiedades rurales en todos los estados. Haga clic para explorar destinos de turismo rural.',
    'map.states': 'Estados',
    'map.viewAllStates': 'Ver todos los estados',
    'map.allProperties': 'Todas las propiedades',
    'map.changeState': 'Cambiar estado',
    'map.close': 'Cerrar',
    'map.clickNavigate': 'Haga clic para navegar en el mapa',
    'map.propertiesIn': 'Propiedades en',
    'map.viewFullDetails': 'Ver Detalles Completos',
    'map.activities': 'Actividades:',
    'map.perPerson': '/ persona',

    // Footer
    'footer.desc': 'Rural Time – Plataforma de Turismo Rural e Innovación en el Agro. Un proyecto conectado a los valores y objetivos del CNA Jovem.',
    'footer.createdBy': 'Creado por',
    'footer.role': 'Instructor del Senar y Líder del Agro',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.start': 'Inicio',
    'footer.aboutUs': 'Quiénes Somos',
    'footer.bePartner': 'Sea Socio',
    'footer.contact': 'Contacto',
    'footer.contactTitle': 'Contacto',
    'footer.rights': '© 2026 Rural Time. Todos los derechos reservados.',
    'footer.poweredBy': 'Powered by',

    // PropriedadeDetalhes
    'detail.back': 'Volver',
    'detail.featured': 'Destacado',
    'detail.noImage': 'Sin imagen',
    'detail.about': 'Acerca de',
    'detail.viewMore': 'Ver más',
    'detail.viewLess': 'Ver menos',
    'detail.size': 'Tamaño',
    'detail.hectares': 'hectáreas',
    'detail.capacity': 'Capacidad',
    'detail.visitors': 'visitantes',
    'detail.visitPrice': 'Precio de visita',
    'detail.schedule': 'Horario',
    'detail.activities': 'Actividades',
    'detail.infrastructure': 'Infraestructura',
    'detail.contact': 'Contacto',
    'detail.bookVisit': 'Agendar visita',
    'detail.date': 'Fecha',
    'detail.selectDate': 'Seleccione una fecha',
    'detail.people': 'Personas',
    'detail.person': 'persona',
    'detail.persons': 'personas',
    'detail.sendWhatsapp': 'Enviar por WhatsApp',
    'detail.notFound': 'Propiedad no encontrada',
    'detail.backHome': 'Volver al inicio',
    'detail.goToImage': 'Ir a imagen',
    'detail.thumbnail': 'miniatura',

    // General
    'general.ruralTourism': 'Turismo Rural',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key] || translations['pt'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
