-- Inserir propriedades de exemplo
INSERT INTO public.propriedades (
  user_id,
  nome,
  descricao,
  endereco,
  cidade,
  estado,
  cep,
  telefone,
  email,
  tipo_propriedade,
  atividades,
  infraestrutura,
  horario_funcionamento,
  preco_visita,
  capacidade_visitantes,
  tamanho_hectares,
  ativo,
  destaque
) VALUES 
(
  '00000000-0000-0000-0000-000000000000',
  'Adega Vicchini',
  'Tradicional adega familiar com degustação de vinhos artesanais e experiência completa de vinicultura.',
  'Estrada Municipal, 1500',
  'Atibaia',
  'SP',
  '12940-000',
  '11987654321',
  'contato@adegavicchini.com.br',
  'Vinícola',
  ARRAY['Degustação de vinhos', 'Tour pela vinícola', 'Colheita da uva', 'Workshop de vinicultura'],
  ARRAY['Estacionamento', 'Loja de produtos', 'Área de degustação', 'Banheiros'],
  'Segunda a Sábado: 9h às 17h, Domingo: 9h às 15h',
  80.00,
  25,
  15.5,
  true,
  true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Hotel Fazenda Boa Esperança',
  'Hotel fazenda com hospedagem completa e diversas atividades rurais para toda a família.',
  'Rodovia Dom Pedro I, Km 95',
  'Bragança Paulista',
  'SP',
  '12916-000',
  '11976543210',
  'reservas@boaesperanca.com.br',
  'Hotel Fazenda',
  ARRAY['Ordenha de vacas', 'Cavalgada', 'Pesca esportiva', 'Trilha ecológica', 'Alimentação dos animais'],
  ARRAY['Piscina', 'Restaurante', 'Chalés', 'Estacionamento', 'Quadra poliesportiva'],
  'Funcionamento 24h para hóspedes, Visitação: 8h às 17h',
  120.00,
  50,
  45.2,
  true,
  true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Aromas de Bragança',
  'Propriedade especializada em plantas aromáticas e medicinais com workshops e produtos naturais.',
  'Estrada do Taboão, 850',
  'Bragança Paulista',
  'SP',
  '12919-000',
  '11965432109',
  'info@aromasdebraganca.com.br',
  'Fazenda Aromática',
  ARRAY['Workshop de plantas medicinais', 'Colheita de ervas', 'Destilação de óleos essenciais', 'Caminhada sensorial'],
  ARRAY['Laboratório de destilação', 'Estufa de plantas', 'Loja de produtos', 'Área de convivência'],
  'Terça a Domingo: 8h às 16h',
  60.00,
  20,
  8.3,
  true,
  false
),
(
  '00000000-0000-0000-0000-000000000000',
  'A Lagarta Sucateira',
  'Espaço ecológico com foco em sustentabilidade, reciclagem criativa e educação ambiental.',
  'Sítio Cachoeira Grande, s/n',
  'Nazaré Paulista',
  'SP',
  '12960-000',
  '11954321098',
  'contato@lagartasucateira.org.br',
  'Projeto Ecológico',
  ARRAY['Oficina de reciclagem', 'Arte com sucata', 'Educação ambiental', 'Horta orgânica', 'Compostagem'],
  ARRAY['Oficina de arte', 'Horta comunitária', 'Composteira', 'Área de convivência', 'Banheiro ecológico'],
  'Quinta a Domingo: 9h às 16h',
  45.00,
  30,
  12.0,
  true,
  false
);