// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbljnxjcwcmnzqidgbvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibGpueGpjd2NtbnpxaWRnYnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDc2NDAsImV4cCI6MjA3MTcyMzY0MH0.zGMADtb7KRQwos_PaQ0Y7pcbmITAYwzjXd71nuQq5Dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});